### ISSUE TITLE
💡Реализовать композиционный класс UserInfoManager

### ISSUE THREAD

**Issue by GoldSwanGH** [ComboMeal-Software/project-management-system#15]
Думаю, что достаточно вытащить методы из User в новый класс

**Comment by RealThomasMiles** [comment]
Правильно думаешь!
![1-16690-128](https://user-images.githubusercontent.com/30018684/71308950-5ce96680-2413-11ea-847f-f0aeed9646f6.png)

**Comment by GoldSwanGH** [comment]
#22 Сделал UserInfoManager
