### ISSUE TITLE
Реализовать класс Project

### ISSUE THREAD

**Issue by RealThomasMiles** [ComboMeal-Software/project-management-system#5]
Работаем!

**Comment by RealThomasMiles** [comment]
Сделал header с абстрактным классом и двумя наследниками. Классы пока пустоголовые, надо добавить композиционные классы.

**Comment by RealThomasMiles** [comment]
Надо писать методы!

**Comment by GoldSwanGH** [comment]
Работаем!

**Comment by RealThomasMiles** [comment]
Написание класса завершено #17, #18.
Было принято решение, что абстракция нам не понадобится, класс будет заменен на обычный, два дочерних будут удалены.

**Comment by RealThomasMiles** [comment]
#21
Реализация класса Project завершена!
