### ISSUE TITLE
Реализовать класс User

### ISSUE THREAD

**Issue by GoldSwanGH** [ComboMeal-Software/project-management-system#6]

**Comment by RealThomasMiles** [comment]
Удачи, бро!

**Comment by GoldSwanGH** [comment]
Сделал header для класса User

**Comment by GoldSwanGH** [comment]
Сделал класс User. Еще нужно будет доделать композиционные, но в целом он готов!

**Comment by RealThomasMiles** [comment]
Круто! Работаем!
![1-5280-128](https://user-images.githubusercontent.com/30018684/71308994-e7ca6100-2413-11ea-812f-8ebc8d5a85d0.png)
